### ISSUE TITLE
etc/flowforge.yml db.user should be db.username

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#178]
```
db:
  logging: false
  ## The database type: sqlite|postgres
  type: sqlite

  ### SQLite options

  ## The database filename. Relative to $FLOWFORGE_HOME/var/
  ## Set to ':memory:' for a database that is wiped on restart
  storage: forge.db

  ### Postgres options

  # host: localhost
  # user: forge
  # password: secret
```

Should be 

```db:
  logging: false
  ## The database type: sqlite|postgres
  type: sqlite

  ### SQLite options

  ## The database filename. Relative to $FLOWFORGE_HOME/var/
  ## Set to ':memory:' for a database that is wiped on restart
  storage: forge.db

  ### Postgres options

  # host: localhost
  # username: forge
  # password: secret

```

See https://github.com/flowforge/flowforge/blob/03b5ea492c72c64c8367fcb9a271d3a8a32cb15e/forge/db/index.js#L46
