### ISSUE TITLE
Cannot use Google SMTP server: smtp-relay.gmail.com. Encrypted SMTP is using sslv3.

### ISSUE THREAD

**Issue by johnebgood** [FlowFuse/flowfuse#2953]
### Current Behavior

I used the AWS Marketplace AMI. I attempted to use my Google workspaces gmail account for email using smtp-relay.gmail.com following Google's instructions: https://support.google.com/a/answer/2956491

Getting this in the docker logs:

{"level":"ERROR","time":"2023-10-16T05:39:03.225Z","msg":"Failed to verify email connection: Error: 140527946771248:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:\n"}

### Expected Behavior

SSLv3 is deprecated, all secure smtp communications should use TLS or have the option. Google has an option to use unencrypted communications from a specified IP without a username/password however the SMTP configuration doesn't allow not using a username/password.

### Steps To Reproduce

Configure email to use Google SMTP servers.

### Environment

Using the AWS AMI from the marketplace with no modifications.

From the logs:
FlowFuse v1.12.2
FlowFuse running with NodeJS v16.20.2

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by hardillb** [comment]
Can you please log into the AWS EC2 machine and provide the email section from the `/opt/flowforge/etc/flowforge.yml` file please (replace the username/password with placeholder values)

**Comment by johnebgood** [comment]
I got it working unencrypted for now. I was able to comment out the username/password and set secure to false and I'm able to use unauthenticated Gmail SMTP access with specified IP of the instance. The /opt/flowforge/first-login.sh does not allow leaving username/password blank. I would still like to get TLS working however. I'm looking into the code to see if there's a hidden option or something I could help contribute.

Below is the configuration for unencrypted Gmail SMTP relay:

email:
  enabled: true
  from: '"FlowForge" <flowforge@mydomain.com>'
  smtp:
    host: smtp-relay.gmail.com
    port: 587
    secure: false

<img width="1266" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/663211/342f79c2-a6cb-4aa5-929f-248e92a91fc2">

**Comment by johnebgood** [comment]
Did not intend to close, just wanted to comment. Now I know that is a button. 😃 

Looking into TLS possibilities.

**Comment by hardillb** [comment]
If you get a moment can you try the following config:

```
email:
  enabled: true
  from: '"FlowForge" [flowforge@mydomain.com](mailto:flowforge@mydomain.com)'
  smtp:
    service: 'gmail'
    auth:
      user: username
      pass: password
```

and

```
email:
  enabled: true
  from: '"FlowForge" [flowforge@mydomain.com](mailto:flowforge@mydomain.com)'
  smtp:
    service: 'gmail'
    host: 'smtp-relay.gmail.com'
    port: 587
    secure: true
    tls:
      ciphers: "TLSv1.2",
    auth:
      user: username
      pass: password
```
