### ISSUE TITLE
Automatic 'First Setup' using flowforge.yml

### ISSUE THREAD

**Issue by beasteers** [FlowFuse/flowfuse#3443]
### Description

Right now, when you bring up a FlowFuse instance, you have to go through a manual [First Setup process](https://flowfuse.com/docs/install/first-run/). 

It would be great if flowfuse could use the config to skip the manual entry:

(environment variable expansion needed for security/portability)
```yaml

admin:
  full_name: $ADMIN_NAME
  email: $ADMIN_EMAIL
  username: $ADMIN_USERNAME
  password: $ADMIN_PASSWORD

settings:
  license_key: $LICENSE_KEY
  enable_anonymous_statistics: true

teams:
 - name: Dev
   applications:
    - name: Ingestion
      description: Data Ingestion
      # create_instance: true
      # instance_name: auto
      # instance_type: default
      # instance_stack: default

      # NodeRed Projects:
      project_repo: git@github.com:user/my-node-red-projects-repo.git
      # project_branch: main
```
Scripting it doesn't seem like the right way to go since the endpoints use crsf tokens and I assume those checks are already being done during the bring up process.

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member
