### ISSUE TITLE
Improve Instance Startup Time

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3529]
### Description

When using FF Cloud, the startup time for instances is slow, too slow. We've hidden this well with the onboarding, but it would be useful to improve this during the general instance spin up too.

Made this an Epic as I'm sure there are multiple angles we could go here, but it needs to be recorded and investigated.

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise
```[tasklist]
### Related
- [ ] https://github.com/FlowFuse/CloudProject/issues/369
- [ ] https://github.com/FlowFuse/flowfuse/issues/3058
```

**Comment by joepavitt** [comment]
Same goes for installation of packages too, I know this is a CPU limitation e.g. on "Small" instances, but want to at least ask the question

**Comment by hardillb** [comment]
We did think about using a sidecar pod without the CPU limitations to do the initial install of packages, but the k8s scheduler takes the highest value of all containers in a pod to determine the resources needed and to decide how many pods can be scheduled on a given node.

This would vastly reduce the number we can pack on to a node and impact margins.

**Comment by ppawlowski** [comment]
> We did think about using a sidecar pod without the CPU limitations to do the initial install of packages, but the k8s scheduler takes the highest value of all containers in a pod to determine the resources needed and to decide how many pods can be scheduled on a given node.
> 
> This would vastly reduce the number we can pack on to a node and impact margins.

That is valid untill you apply limits on the init container too. If we don't set any cpu limits for init container it will not affec effective CPU limits for whole pod.
Just to be sure about the above, I have created a following pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: cpu-limits-stress-v6
spec:
  nodeSelector:
    kubernetes.io/hostname: ip-192-168-23-15.eu-west-1.compute.internal
  initContainers:
    - name: pod-cpu-init-stressor
      image: narmidm/k8s-pod-cpu-stressor:1.0.0
      args:
        - "-cpu=1"
        - "-duration=600s"
  containers:
    - name: pod-cpu-stressor
      image: narmidm/k8s-pod-cpu-stressor:1.0.0
      args:
        - "-cpu=1"
        - "-duration=600s"
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m
``` 

In short, init container is created without cpu limits, using 1vCPU for 10 minutes. Container is using same cpu stress parameters but it has 0.1 soft and 0.2 hard cpu limits set.
The CPU usage is as follows for one lifecycle for thus pod:

![Zrzut ekranu 2024-03-14 o 19 25 12](https://github.com/FlowFuse/flowfuse/assets/7622533/16bc99d5-2841-4366-9ecf-6bffd63080b0)

As we can see, init container was using as much as it could while regular one was limited by the resources constraints. 
Also, since init container does not have any soft limits, they are not taken into the account during pod scheduling.
